export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'https://api.truthlayer.io';
export const CACHE_TTL = 24 * 60 * 60;
export const MAX_DAILY_ANALYSIS_FREE = 50;
export const MAX_DAILY_ANALYSIS_PRO = 2000;

export const TRUST_SCORE_THRESHOLDS = {
  HIGH: 70,
  MEDIUM: 40,
  LOW: 0
};

export const DARK_PATTERN_TYPES = {
  URGENCY: 'urgency',
  SOCIAL_PROOF: 'social_proof',
  HIDDEN_COSTS: 'hidden_costs',
  ROACH_MOTEL: 'roach_motel',
  CONFIRMSHAMING: 'confirmshaming',
  MISDIRECTION: 'misdirection',
  PRIVACY_ZUCKERING: 'privacy_zuckering',
  DISGUISED_ADS: 'disguised_ads'
} as const;

export const KNOWN_TRACKERS = [
  'google-analytics.com',
  'googletagmanager.com',
  'doubleclick.net',
  'facebook.net',
  'hotjar.com',
  'mixpanel.com',
  'segment.io',
  'amplitude.com',
  'hubspot.com',
  'linkedin.com/analytics',
  'twitter.com/analytics',
  'pinterest.com/analytics',
  'reddit.com/analytics',
  'tiktok.com/analytics',
  'snapchat.com/analytics',
  'quantserve.com',
  'scorecardresearch.com',
  'comscore.com',
  'adzerk.net',
  'criteo.com',
  'taboola.com',
  'outbrain.com',
  'casalemedia.com',
  'rubiconproject.com',
  'openx.net',
  'pubmatic.com',
  'indexexchange.com',
  'sovrn.com',
  'media.net',
  'amazon-adsystem.com',
  'adnxs.com',
  'adsrvr.org',
  'tidaltv.com',
  'appnexus.com',
  'spotx.tv',
  'gumgum.com',
  'improvedigital.com',
  'richaudience.com',
  'smartadserver.com',
  'smaato.com',
  'tremorhub.com',
  'triplelift.com',
  'undertone.com',
  'verizonmedia.com',
  'yahoo.com/analytics',
  'bing.com/analytics',
  'newrelic.com',
  'datadoghq.com',
  'fullstory.com',
  'mouseflow.com',
  'clicktale.net',
  'crazyegg.com',
  'optimizely.com',
  'vwo.com',
  'abtasty.com',
  'launchdarkly.com',
  'rollbar.com',
  'sentry.io',
  'logrocket.com',
  'heap.io',
  'amplitude.com',
  'posthog.com',
  'matomo.org',
  'piwik.pro',
  'adobe.com/analytics',
  'salesforce.com/analytics',
  'braze.com',
  'customer.io',
  'intercom.io',
  'drift.com',
  'olark.com',
  'tidio.com',
  'crisp.chat',
  'user.com',
  'segment.com',
  'mparticle.com',
  'tealium.com',
  'ensighten.com',
  'akamai.com/analytics',
  'cloudflare.com/analytics',
  'fastly.com/analytics',
  'stackpath.com/analytics',
  'perimeterx.com',
  'distilnetworks.com',
  'shapesecurity.com',
  'imperva.com',
  'cloudfront.net',
  'jsdelivr.net',
  'unpkg.com',
  'cdnjs.com',
  'adroll.com',
  'bluekai.com',
  'exelator.com',
  'lotame.com',
  'drawbridge.com',
  'demandbase.com',
  '6sense.com',
  'zoominfo.com',
  'leadfeeder.com',
  'clearbit.com',
  'fullcontact.com',
  'livechat.com',
  'zendesk.com',
  'freshwork.com',
  'hubspot.com/analytics',
  'pardot.com',
  'marketo.com',
  'eloqua.com',
  'act-on.com',
  'mailchimp.com',
  'constantcontact.com',
  'sendgrid.com',
  'mailgun.com',
  'postmarkapp.com',
  'convertkit.com',
  'getresponse.com',
  'activecampaign.com',
  'clickfunnels.com',
  'unbounce.com',
  'instapage.com',
  'optimize.google.com'
];

export const MSG_TYPE = {
  REQUEST_ANALYSIS: 'REQUEST_ANALYSIS',
  ANALYSIS_COMPLETE: 'ANALYSIS_COMPLETE',
  CACHE_GET: 'CACHE_GET',
  CACHE_SET: 'CACHE_SET'
} as const;
